"""Module containing utils methods than can be used outside of tokenization."""

from .split import (
    get_average_num_tokens_per_note,
    split_files_for_training,
    split_score_per_beats,
    split_score_per_note_density,
    split_score_per_ticks,
    split_score_per_tracks,
    split_seq_in_subsequences,
    split_tokens_files_to_subsequences,
)
from .utils import (
    compute_ticks_per_bar,
    compute_ticks_per_beat,
    concat_scores,
    convert_ids_tensors_to_list,
    detect_chords,
    filter_dataset,
    fix_offsets_overlapping_notes,
    get_bars_ticks,
    get_beats_ticks,
    get_num_notes_per_bar,
    get_score_programs,
    get_score_ticks_per_beat,
    is_track_empty,
    merge_same_program_tracks,
    merge_scores,
    merge_tracks,
    merge_tracks_per_class,
    num_bar_pos,
    remove_duplicated_notes,
)

__all__ = [
    "compute_ticks_per_bar",
    "compute_ticks_per_beat",
    "concat_scores",
    "convert_ids_tensors_to_list",
    "detect_chords",
    "filter_dataset",
    "fix_offsets_overlapping_notes",
    "get_average_num_tokens_per_note",
    "get_bars_ticks",
    "get_beats_ticks",
    "get_num_notes_per_bar",
    "get_score_programs",
    "get_score_ticks_per_beat",
    "is_track_empty",
    "merge_same_program_tracks",
    "merge_scores",
    "merge_tracks",
    "merge_tracks_per_class",
    "num_bar_pos",
    "remove_duplicated_notes",
    "split_files_for_training",
    "split_score_per_beats",
    "split_score_per_note_density",
    "split_score_per_ticks",
    "split_score_per_tracks",
    "split_seq_in_subsequences",
    "split_tokens_files_to_subsequences",
]
