name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - run: uv sync --extra tests
      - run: uv run ruff check
        env:
          RUFF_OUTPUT_FORMAT: github
      - run: uv run ruff format --check
        env:
          RUFF_OUTPUT_FORMAT: github
      #- run: uv run ty check --output-format github
